int augment_img(unsigned char* img_data, int c, int h, int w, unsigned char* aug_img_data, int c1, int h1, int w1,
    bool rand_crop,
        int crop_x_start,
        int crop_y_start,
        float max_rotate_angle,
        float max_aspect_ratio,
        float max_shear_ratio,
        int max_crop_size,
        int min_crop_size,
        float max_random_scale,
        float min_random_scale,
        float max_img_size,
        float min_img_size,
        float random_h,
        float random_s,
        float random_l,
        float rotate,
        int fill_value,
        int inter_method,
        int pad,
        bool rand_mirror,
        int nlandmarks, float* landmarks_x, float*landmarks_y );
